-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggxsR6Vn/VIwyTKla
IR1cQybxNXBSU5cnE1kH/HLHssGgCgYIKoZIzj0DAQehRANCAARaNNMDW09Xijex
6lDh3fKRoVGGvwB+uxETnGLRoaVJg8zJdBas4PODCN1eMyh3eiI0kKu85Tr3FqiM
urybKzUg
-----END PRIVATE KEY-----