// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWEAo7NGknOBrHmHUfLMBYrHyAu5Ij6U',
    appId: '1:494958716962:web:fb1113f93d55e209ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    authDomain: 'bourboneur.firebaseapp.com',
    storageBucket: 'bourboneur.firebasestorage.app',
    measurementId: 'G-LSN2MK84CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMES6y9lcoqdPT5qmvA_3G5AQ9ZOZBms',
    appId: '1:570904028386:android:5ad7da3729a25e13c6aabb',
    messagingSenderId: '570904028386',
    projectId: 'bourboneur-c374d',
    storageBucket: 'bourboneur-c374d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7pcPqzM3Ojj4Qlf_b0uPr22dhuw5dvgE',
    appId: '1:570904028386:ios:9f5836bb8c7d2625c6aabb',
    messagingSenderId: '570904028386',
    projectId: 'bourboneur-c374d',
    storageBucket: 'bourboneur-c374d.firebasestorage.app',
    iosBundleId: 'com.app.bourboneur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRTX1-whuEcFsHpCv_CsdE2d8KoKxEhkA',
    appId: '1:494958716962:ios:506057dff5cadb12ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    storageBucket: 'bourboneur.firebasestorage.app',
    iosBundleId: 'com.example.bourboneur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmWEAo7NGknOBrHmHUfLMBYrHyAu5Ij6U',
    appId: '1:494958716962:web:cf6f621bb08a4a01ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    authDomain: 'bourboneur.firebaseapp.com',
    storageBucket: 'bourboneur.firebasestorage.app',
    measurementId: 'G-QE9QHZ9YZL',
  );
}
