// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWEAo7NGknOBrHmHUfLMBYrHyAu5Ij6U',
    appId: '1:494958716962:web:fb1113f93d55e209ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    authDomain: 'bourboneur.firebaseapp.com',
    storageBucket: 'bourboneur.firebasestorage.app',
    measurementId: 'G-LSN2MK84CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6qMLuAi2RGC9UxQjZhCqgMFodMzxQykA',
    appId: '1:1078950606869:android:0bae066b997fbb94e5761c',
    messagingSenderId: '1078950606869',
    projectId: 'oakspireclub',
    storageBucket: 'oakspireclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpCdjwqnY8HlIxOVk99DDGi9Dyq18sI8',
    appId: '1:1078950606869:ios:b99a49f8e64cb8f7e5761c',
    messagingSenderId: '1078950606869',
    projectId: 'oakspireclub',
    storageBucket: 'oakspireclub.firebasestorage.app',
    iosBundleId: 'com.oakspire.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRTX1-whuEcFsHpCv_CsdE2d8KoKxEhkA',
    appId: '1:494958716962:ios:506057dff5cadb12ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    storageBucket: 'bourboneur.firebasestorage.app',
    iosBundleId: 'com.example.bourboneur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmWEAo7NGknOBrHmHUfLMBYrHyAu5Ij6U',
    appId: '1:494958716962:web:cf6f621bb08a4a01ad427b',
    messagingSenderId: '494958716962',
    projectId: 'bourboneur',
    authDomain: 'bourboneur.firebaseapp.com',
    storageBucket: 'bourboneur.firebasestorage.app',
    measurementId: 'G-QE9QHZ9YZL',
  );
}
